#!/usr/bin/env python3
# ABOUTME: Bundle the calculator package into a single self-contained Marimo file.
# ABOUTME: Marimo WASM (Pyodide) can't resolve `from calculator.X import Y` because
# ABOUTME: Pyodide doesn't have access to the local filesystem. This script reads
# ABOUTME: calculator/*.py modules, registers them as in-memory modules at the top
# ABOUTME: of the notebook, then rewrites the marimo_app.py to use them.
#
# Output: calculator/marimo_app_wasm.py (gitignored — regenerated on every build)
#
# The bundling strategy:
# 1. Add PEP 723 inline script metadata so Pyodide installs PyPI deps
#    (marimo, plotly, pyyaml, click).
# 2. Emit a bootstrap cell that registers each calculator/*.py as a synthetic
#    module via `sys.modules` and `types.ModuleType`. Modules execute in dep
#    order (confidence -> workload_profiles -> permalink -> readiness -> lcpr
#    -> view_registry).
# 3. Append the original marimo_app.py contents AFTER the bootstrap — the
#    existing `from calculator.X import Y` statements will then resolve.

from __future__ import annotations

import sys
from pathlib import Path


PEP723_HEADER = '''# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "marimo>=0.10",
#     "plotly>=5.22",
#     "pyyaml>=6.0",
#     "click>=8.1",
# ]
# ///
'''


# Dependency-ordered list. Earlier modules must not import from later ones.
BUNDLE_ORDER = [
    "confidence",
    "workload_profiles",
    "permalink",
    "readiness",
    "lcpr",
    "view_registry",
]


def _strip_provider_pricing_yaml_dep(text: str) -> str:
    """The lcpr/workload_profiles modules read provider_pricing.yaml from disk.
    In WASM, the file is bundled into Pyodide's virtual FS by Marimo's static
    asset handling — but only if we tell Marimo about it. For the initial
    bundle, the user can pass the YAML content via a synthetic in-memory
    constant. Currently NO modification — this hook is reserved for future
    use if the lcpr.py path-handling needs in-WASM patching.
    """
    return text


def emit_bundle(src_root: Path, marimo_app_path: Path, out_path: Path) -> None:
    parts: list[str] = []
    parts.append(PEP723_HEADER)
    parts.append("")
    parts.append("# ABOUTME: GENERATED FILE — do not edit by hand.")
    parts.append("# ABOUTME: Generated by scripts/bundle_marimo_for_wasm.py from marimo_app.py + calculator/*.py")
    parts.append("# ABOUTME: Bundles the calculator package inline so Marimo's WASM (Pyodide)")
    parts.append("# ABOUTME: can run without filesystem access. Regenerated on every build.")
    parts.append("")

    # Build the bootstrap code that registers the calculator package + writes
    # provider_pricing.yaml + marimo-theme.css to Pyodide's /tmp/. This code
    # MUST run inside a @app.cell because Marimo's WASM export strips top-level
    # statements outside of cells. We inject it as a single string that gets
    # exec()'d at the top of the _imports cell.

    bootstrap_lines: list[str] = [
        "import sys, types, os",
        # Pyodide doesn't auto-install from PEP 723 metadata in all marimo",
        # versions — explicit micropip.install is the bulletproof path.",
        "if sys.platform == 'emscripten':",
        "    import micropip",
        "    await micropip.install(['plotly', 'pyyaml'])",
        "_calc_pkg = types.ModuleType('calculator')",
        "_calc_pkg.__path__ = []",
        "sys.modules['calculator'] = _calc_pkg",
    ]
    for mod_name in BUNDLE_ORDER:
        mod_path = src_root / f"{mod_name}.py"
        if not mod_path.exists():
            print(f"WARNING: {mod_path} not found; skipping")
            continue
        mod_src = mod_path.read_text()
        mod_src = _strip_provider_pricing_yaml_dep(mod_src)
        # We need to escape the source so it can live inside a """ string.
        # Use a doubled-quote escape strategy. We'll use the !r repr trick for safety.
        escaped = repr(mod_src)
        bootstrap_lines.append(f"_m = types.ModuleType('calculator.{mod_name}')")
        bootstrap_lines.append(f"_m.__file__ = '<bundled calculator.{mod_name}>'")
        bootstrap_lines.append(f"_m.__package__ = 'calculator'")
        bootstrap_lines.append(f"sys.modules['calculator.{mod_name}'] = _m")
        bootstrap_lines.append(f"setattr(_calc_pkg, '{mod_name}', _m)")
        bootstrap_lines.append(f"exec({escaped}, _m.__dict__)")

    # Bundle the YAML to /tmp/
    yaml_path = src_root / "provider_pricing.yaml"
    if yaml_path.exists():
        yaml_text = yaml_path.read_text()
        bootstrap_lines.append("os.makedirs('/tmp', exist_ok=True)")
        bootstrap_lines.append(f"open('/tmp/provider_pricing.yaml', 'w').write({yaml_text!r})")

    # Bundle the marimo-theme.css to /tmp/
    theme_css_path = src_root / "static" / "marimo-theme.css"
    if theme_css_path.exists():
        theme_css_text = theme_css_path.read_text()
        bootstrap_lines.append(f"open('/tmp/_marimo-theme.css', 'w').write({theme_css_text!r})")

    # The whole bootstrap goes into a single string we exec at the top of _imports.
    bootstrap_blob = "\n".join(bootstrap_lines)

    # Now read marimo_app.py and inject the bootstrap into the _imports cell.
    # Also patch path references for WASM.
    marimo_app_src = marimo_app_path.read_text()

    # Patch the pricing_path resolution so it uses /tmp/ in WASM
    marimo_app_src = marimo_app_src.replace(
        'pricing_path = Path(__file__).parent / "provider_pricing.yaml"',
        'pricing_path = Path("/tmp/provider_pricing.yaml")  # WASM-bundled; see _imports cell',
    )

    # Patch the theme_css cell to use the /tmp/ bundled css
    marimo_app_src = marimo_app_src.replace(
        '_css_path = Path(__file__).parent / "static" / "marimo-theme.css"',
        '_css_path = Path("/tmp/_marimo-theme.css")  # WASM-bundled in _imports cell',
    )

    # Inject the bootstrap as the very first line inside _imports cell body.
    # The _imports cell looks like:
    #   @app.cell
    #   def _imports():
    #       import marimo as mo
    #       ...
    # We want:
    #   @app.cell
    #   def _imports():
    #       # WASM bootstrap (bundled calculator package + provider_pricing.yaml + marimo-theme.css)
    #       exec(<bootstrap-blob>, globals(), locals())  # noqa
    #       import marimo as mo
    #       ...
    # Since we can't easily exec into the function's local scope (locals() returns a copy
    # in CPython), we instead inject the bootstrap statements directly (de-stringed) as
    # the first line of the function body.
    bootstrap_indented = "\n".join("    " + line for line in bootstrap_lines)
    inject_marker = "def _imports():\n"
    if inject_marker not in marimo_app_src:
        print("ERROR: could not find _imports cell marker in marimo_app.py")
        sys.exit(2)
    # Make the cell async since the bootstrap uses `await micropip.install(...)`.
    # Marimo supports async cells natively.
    marimo_app_src = marimo_app_src.replace(
        "def _imports():\n",
        "async def _imports():\n",
    )
    inject_marker = "async def _imports():\n"
    insert_after = marimo_app_src.index(inject_marker) + len(inject_marker)
    marimo_app_src = (
        marimo_app_src[:insert_after]
        + "    # === BUNDLED FOR WASM: bootstrap calculator package + assets ===\n"
        + bootstrap_indented
        + "\n    # === END BOOTSTRAP ===\n"
        + marimo_app_src[insert_after:]
    )

    parts.append(marimo_app_src)

    out_path.write_text("\n".join(parts) + "\n")
    print(f"OK: wrote {out_path} ({out_path.stat().st_size:,} bytes)")


def main() -> int:
    here = Path(__file__).parent.parent  # repo root
    src_root = here / "calculator"
    marimo_app = src_root / "marimo_app.py"
    out_path = src_root / "marimo_app_wasm.py"
    if not marimo_app.exists():
        print(f"ERROR: {marimo_app} not found")
        return 1
    emit_bundle(src_root, marimo_app, out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
